n=mos_deep_med
sex $n.fits -c astrom.sex -CATALOG_NAME astrefcat.cat -CATALOG_TYPE FITS_LDAC \
-PARAMETERS_NAME astrom.param -DETECT_THRESH 2.0 -ANALYSIS_THRESH 2.0 \
-WEIGHT_TYPE MAP_WEIGHT -WEIGHT_IMAGE $n.weight.fits -WEIGHT_THRESH 0 \
-BACK_TYPE AUTO -MEMORY_BUFSIZE 4096
